name: Package and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV

    - name: Set up environment
      run: sudo apt-get install zip

    - name: Run package script
      run: ./package.sh

    - name: Test
      run: unzip -t birbs-*-desktop.zip && unzip -t birbs-*-organelle.zip

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          birbs-*-desktop.zip
          birbs-*-organelle.zip
